Fix broken v1.2.0 (#88)
# Why
The v1.2.0 is broken by error
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/gdunit4-action-test/gdunit4-action-test/.gdunit4_action/versioning'. Did you forget to run actions/checkout before running your local action?
```


# What
Reading the workaround to copy the sub action files into current git
work directory,